version: "3.8"

x-analyzer-base:
  &analyzer-base
  image: migalabs/goteth:v2.0.0

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    networks: [ cluster ]
    ports:
      - ${DB_PUBLIC_PORT:-5434}:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes: 
      - ./postgresql/init-database.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgresql/trigger_val_window.sql:/trigger_val_window.sql
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U user -d ethseer
      interval: 10s
      timeout: 3s
      retries: 3

  ethseer-client:
    image: migalabs/ethseer-client:${ETHSEER_CLIENT_TAG:-v1.3.0}
    networks: [ cluster ]
    init: true
    restart: unless-stopped
    
  ethseer-server:
    image: migalabs/ethseer-server:${ETHSEER_SERVER_TAG:-v1.3.0}
    environment:
      - CALLS_VERBOSE=${CALLS_VERBOSE:-True}
      - API_LISTEN_PORT=3020
      - API_LISTEN_IP=0.0.0.0
      - DB_USER=${DB_USER:-user}
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-ethseer}
      - DB_PORT=${DB_PORT:-5432}
      - DB_PASSWORD=${DB_PASSWORD:-password}
    init: true
    restart: unless-stopped
    networks: [ cluster ]
    
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - ${NGINX_PORT:-80}:5085
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks: [ cluster ]
    depends_on:
      - ethseer-client
      - ethseer-server
                        
  analyzer:
    <<: *analyzer-base
    network_mode: 'host'
    init: true
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: >-
      blocks
      --log-level=${ANALYZER_LOG_LEVEL:-info}
      --bn-endpoint=${ANALYZER_BN_ENDPOINT:-localhost:5052}
      --el-endpoint=${ANALYZER_EL_ENDPOINT:-localhost:8545}
      --init-slot=${ANALYZER_INIT_SLOT:-0}
      --final-slot=${ANALYZER_FINAL_SLOT:-1000}
      --db-url=${ANALYZER_DB_URL:-postgresql://user:password@localhost:5434/ethseer}
      --workers-num=${ANALYZER_WORKERS_NUM:-1}
      --db-workers-num=${ANALYZER_DB_WORKERS_NUM:-1}
      --download-mode=${ANALYZER_DOWNLOAD_MODE:-finalized}
      --metrics=${ANALYZER_METRICS:-epoch,block}
      --prometheus-port=${BLOCK_PROMETHEUS_PORT:-9081}

networks:
  cluster: