version: "3.8"

x-goteth-base:
  &goteth-base
  image: migalabs/goteth:v2.0.0

services:

  db:
    image: postgres:14.1-alpine
    restart: always
    networks: [ cluster ]
    ports:
      - 127.0.0.1:${DB_PUBLIC_PORT:-5434}:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes: 
      - ./postgresql/init-database.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
      - ./postgresql/trigger_val_window.sql:/trigger_val_window.sql
      - ./data/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U user -d ethseer
      interval: 10s
      timeout: 3s
      retries: 3

  ethseer-client:
    image: migalabs/ethseer-client:${ETHSEER_CLIENT_TAG:-v2.0.0}
    networks: [ cluster ]
    init: true
    restart: unless-stopped
    environment:
      - API_URL=http://ethseer-server:3020
    
  ethseer-server:
    image: migalabs/ethseer-server:${ETHSEER_SERVER_TAG:-v2.0.0}
    environment:
      - CALLS_VERBOSE=${CALLS_VERBOSE:-True}
      - API_LISTEN_PORT=3020
      - API_LISTEN_IP=0.0.0.0
      - NETWORKS=${NETWORKS}
    init: true
    ports:
      - 127.0.0.1:3020:3020
    restart: unless-stopped
    networks: [ cluster ]
    depends_on:
      db:
        condition: service_healthy
    
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - ${NGINX_PORT:-3010}:5085
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks: [ cluster ]
    depends_on:
      - ethseer-client
      - ethseer-server
                        
  goteth:
    <<: *goteth-base
    network_mode: 'host'
    init: true
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    command: >-
      blocks
      --log-level=${GOTETH_LOG_LEVEL:-info}
      --bn-endpoint=${GOTETH_BN_ENDPOINT:-localhost:5052}
      --el-endpoint=${GOTETH_EL_ENDPOINT:-localhost:8545}
      --init-slot=${GOTETH_INIT_SLOT:-0}
      --final-slot=${GOTETH_FINAL_SLOT:-1000}
      --db-url=${GOTETH_DB_URL:-postgresql://user:password@localhost:5434/ethseer?sslmode=disable}
      --workers-num=${GOTETH_WORKERS_NUM:-1}
      --db-workers-num=${GOTETH_DB_WORKERS_NUM:-1}
      --download-mode=${GOTETH_DOWNLOAD_MODE:-finalized}
      --metrics=${GOTETH_METRICS:-epoch,block}
      --prometheus-port=${GOTETH_PROMETHEUS_PORT:-9081}

networks:
  cluster: