# Fuente: https://github.com/vercel/next.js/blob/canary/examples/with-docker/README.md

ARG ETHSEER_CLIENT_VERSION

# Install dependencies only when needed
FROM migalabs/ethseer-client:$ETHSEER_CLIENT_VERSION AS deps
RUN yarn install --frozen-lockfile
# Rebuild the source code only when needed
FROM node:16-alpine AS builder

ARG NGINX_PORT
ARG NEXT_PUBLIC_URL_API
ARG NEXT_PUBLIC_GOOGLE_ANALYTICS
ARG NEXT_PUBLIC_TAG_MANAGER
ARG NEXT_PUBLIC_NETWORK_GENESIS

ENV NGINX_PORT=$NGINX_PORT
ENV ETHSEER_CLIENT_VERSION=$ETHSEER_CLIENT_VERSION
ENV NEXT_PUBLIC_URL_API $NEXT_PUBLIC_URL_API
ENV NEXT_PUBLIC_GOOGLE_ANALYTICS $NEXT_PUBLIC_GOOGLE_ANALYTICS
ENV NEXT_PUBLIC_TAG_MANAGER $NEXT_PUBLIC_TAG_MANAGER
ENV NEXT_PUBLIC_NETWORK_GENESIS $NEXT_PUBLIC_NETWORK_GENESIS

RUN env > .env

WORKDIR /app
COPY --from=deps /app/ ./
RUN yarn build

# Production image, copy all the files and run next
FROM node:16-alpine AS runner
WORKDIR /app

ENV NODE_ENV production

RUN addgroup -g 1001 -S nodejs
RUN adduser -S nextjs -u 1001

# You only need to copy next.config.js if you are NOT using the default configuration
# COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.env ./.env

# Automatically leverage output traces to reduce image size 
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT 3000

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
# ENV NEXT_TELEMETRY_DISABLED 1

CMD ["node", "server.js"]

# entre 50 a 150 MB